monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!event"]
        console:
            type: console
            channels: ['!event', '!console']

when@sprykerci:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: newrelic
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            newrelic:
                type: newrelic
                app_name: '%env(NEWRELIC_APPNAME)%'
                channels: ["!event"]
                level: info
